# Configuration du profil local. -Dspring-boot.run.profiles=local
spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11435}
      chat:
        model: ${OLLAMA_CHAT_MODEL:qwen3:0.6b}
        temperature: 0
        num-predict: 200

management:
  endpoint:
    health:
      show-details: always